version: '3.8'

services:
  # Service untuk PHP-FPM
  app:
    build:
      context: .  # Direktori yang berisi Dockerfile
      dockerfile: Dockerfile
    container_name: php-fpm-container
    volumes:
      - ./path/to/your/app:/var/www/html  # Ganti dengan path yang sesuai
    networks:
      - mynetwork
    expose:
      - "9000"  # Membuka port PHP-FPM agar bisa diakses oleh Nginx
    environment:
      - SSL_MODE=off
      - AUTORUN_ENABLED=true
      - PHP_OPCACHE_ENABLE=1
      - HEALTHCHECK_PATH=/up

  # Service untuk Nginx
  nginx:
    image: nginx:latest
    container_name: nginx-container
    depends_on:
      - app  # Nginx akan menunggu PHP-FPM berjalan terlebih dahulu
    volumes:
      - ./path/to/your/nginx.conf:/etc/nginx/nginx.conf  # Pastikan mengarahkan ke konfigurasi nginx Anda
      - ./path/to/your/app:/var/www/html  # Volume untuk aplikasi Laravel
    ports:
      - "80:80"  # Port Nginx agar bisa diakses
    networks:
      - mynetwork
    restart: always

  # Jika Anda menggunakan database (MySQL atau PostgreSQL), tambahkan service database seperti berikut:
  # database:
  #   image: mysql:latest
  #   container_name: mysql-container
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_DATABASE: laravel
  #   volumes:
  #     - ./data/mysql:/var/lib/mysql
  #   networks:
  #     - mynetwork
  #   ports:
  #     - "3306:3306"

networks:
  mynetwork:
    driver: bridge
